### ISSUE TITLE
Issue with configMappings

### ISSUE THREAD

**Issue by chrbrnracn** [kafbat/helm-charts#25]
Let me open that issue for you. this is a more suitable place to discuss issues.
The issue refers to PR https://github.com/kafbat/helm-charts/pull/17, which introduces configMappings and secretMappings.

Original quote from PR-discussion
---------------

values.yaml:
```
envs:
  config:
    KAFKA_CLUSTERS_0_NAME: "example1"
    KAFKA_CLUSTERS_0_READONLY: "false"
    KAFKA_CLUSTERS_0_SSL_VERIFYSSL: "false"
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "example:9092"
  configMappings:
    ENV1:
      name: configmap-name
      keyName: configmap-key
```

```
helm install kafbat-ui kafbat-ui/kafka-ui -f values.yaml --namespace xxx --dry-run --version 1.4.2
Error: INSTALLATION FAILED: YAML parse error on kafka-ui/templates/deployment.yaml: error converting YAML to JSON: yaml: line 72: mapping values are not allowed in this context
```

```
helm install kafbat-ui kafbat-ui/kafka-ui -f values.yaml --namespace xxx --dry-run --version 1.4.5
Error: INSTALLATION FAILED: YAML parse error on kafka-ui/templates/deployment.yaml: error converting YAML to JSON: yaml: line 73: mapping values are not allowed in this context
```

@chrbrnracn do you see the problem at first glance?

_Originally posted by @fallen-up in https://github.com/kafbat/helm-charts/issues/17#issuecomment-2376494836_

**Comment by chrbrnracn** [comment]
@fallen-up:

* Does the config map exist (in the same namespace)? Does the key in the config map exist? Please post the structure of the config map.
* What is the result of `helm template --debug`? Find the `configMapKeyRef` section in the deployment and paste what you got there.

**Comment by chrbrnracn** [comment]
I tested your snippet in one of my configurations and cannot reproduce the issue. We need the output of `helm template --debug` to check what the issue could be.
Unfortunately helm isn't very reliable when it comes to error messages and line numbers as it refers to the output, not the template. It could be somewhere above or below line 73 in the template.

**Comment by fallen-up** [comment]
1) problem actual and for secretMapping
2) of course configmap exist in the same namespace. key exist too
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-name
  namespace: xxx
data:
  configmap-key: test
```
3)
```
helm template kafka-ui kafbat-ui/kafka-ui --debug --version 1.4.5  -f values.yaml

install.go:200: [debug] Original chart version: "1.4.5"
install.go:217: [debug] CHART PATH: /home/xxx/.cache/helm/repository/kafka-ui-1.4.5.tgz
Error: YAML parse error on kafka-ui/templates/deployment.yaml: error converting YAML to JSON: yaml: line 73: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 73: mapping values are not allowed in this context
YAML parse error on kafka-ui/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        helm.sh/helm/v3/pkg/action/action.go:170
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:289
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:287
main.newTemplateCmd.func2
        helm.sh/helm/v3/cmd/helm/template.go:88
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.6.1/command.go:968
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1598
```

```
***
      containers:
        - name: kafka-ui
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 2001
          image: custom-image:yyy
          imagePullPolicy: Always
            - name: ENV1
              valueFrom:
                configMapKeyRef:
                  name: configmap-name
                  key: configmap-key
          envFrom:
            - configMapRef:
                name: kafka-ui
***
```

looks like this section doesn't work:
          {{- if or .Values.env  .Values.yamlApplicationConfig .Values.yamlApplicationConfigConfigMap .Values.yamlApplicationConfigSecret }}
          env:

**Comment by fallen-up** [comment]
so it makes more sense to do that in the [example](https://github.com/kafbat/helm-charts/blob/main/charts/kafka-ui/values.yaml#L49):
```
envs:
  secret: {}
  config: {}

env:
  secretMappings: {}
    #ENV_NAME:
    #  name: kubernetes-secret-name
    #  keyName: kubernetes-secret-key
  configMappings: {}
    #ENV_NAME:
    #  name: kubernetes-configmap-name
    #  keyName: kubernetes-configmap-key
```
