### ISSUE TITLE
Error: UPGRADE FAILED: parse error at (kafka-ui/templates/deployment.yaml:57): unclosed action

### ISSUE THREAD

**Issue by odorT** [kafbat/helm-charts#29]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/kafbat/kafka-ui/issues) and [here](https://github.com/kafbat/helm-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/kafbat/kafka-ui/blob/master/.github/SECURITY.md)

### Describe the bug (actual behavior)

it seems new version of kafbat helm chart can't be upgraded anymore

### Expected behavior

installation without errors

### Your installation details

1. https://github.com/kafbat/kafka-ui/commit/2956664
2. kafka-ui-1.4.2
3. 
yamlApplicationConfig:
  kafka:
    clusters:
      - name: test
        bootstrapServers: test.test:9092
        schemaRegistry: http://test1.test1:8081
4. -

### Steps to reproduce

just applying this values fails

**Comment by odorT** [comment]
https://github.com/kafbat/helm-charts/blob/ab4948ba71b99576b7096a120597989a6c869a53/charts/kafka-ui/templates/deployment.yaml#L57

this change broke master

**Comment by odorT** [comment]
any updates on this?

**Comment by azatsafin** [comment]
> any updates on this?

Could you kindly share the complete values file and the specific error message you encountered?

**Comment by odorT** [comment]
command: `helm upgrade --install kafka-ui kafbat-ui/kafka-ui -f values.yaml -n kafka-ui`

output:
```
Release "kafka-ui-deleteme" does not exist. Installing it now.
Error: parse error at (kafka-ui/templates/deployment.yaml:57): unclosed action
```

helm version: `version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}`

values.yaml:
```
replicaCount: 1

route:
  enabled: true

env:
  - name: filtering.groovy.enabled
    value: "true"
  - name: DYNAMIC_CONFIG_ENABLED
    value: "true"

resources:
  requests:
    cpu: '1'
    memory: '1Gi'

yamlApplicationConfig:
  management:
    health:
      ldap:
        enabled: false

volumes:
  - name: config-data
    persistentVolumeClaim:
      claimName: config-pv-claim

volumeMounts:
  - mountPath: "/etc/kafkaui"
    name: config-data

```
